title: Radical Livre
author: Filipe Mosca
url: "https://radical.canalionico.com.br"
description: Blog sobre tecnologia e Linux

defaults:
#defaults para os posts
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /:title
      author: "Filipe Mosca"
#defaults para todo o resto
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# para o SEO tag:
lang: pt_BR

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
