# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Mosquildo
email:
description: >- # this means to ignore newlines until "baseurl:"
  Um blog sobre medicina. Escrevo sobre medicina baseada em evidências, educação médica, casos clínicos e sobre minha vivência na faculdade.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://filipemosca.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: filipemosca
github_username:  filipemosca

# Build settings
plugins:
  - jekyll-sitemap
  # - jekyll-feed
  - jekyll-seo-tag

# markdown: CommonMarkGhPages
# Build settings
markdown: kramdown

commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]

# para o SEO tag:
lang: pt_BR

exclude: ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]

defaults:
#defaults para os posts
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Filipe Mosca"
      permalink: "/:title"
#defaults para todo o resto
  - scope:
      path: "notes"
      type: "pages"
    values:
      layout: "post"
      permalink: "/:basename"
#Imagens
  - scope:
      path: "Jardim/Files/"
    values:
      image: true
      permalink: "/:basename"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
