title: Radical Livre
author: Filipe Mosca
url: "https://filipemosca.github.io"

defaults:
#defaults para os posts
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /:title
#defaults para todo o resto
  - scope:
      path: ""
    values:
      layout: "default"

# para o SEO tag:
lang: pt_BR
